# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Testing with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check licenses with Gradle
        run: ./gradlew checkLicenses
      - name: Build client with Gradle
        run: "./gradlew client:createReleaseDistributable"
      - name: Upload a client Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Client Distribution
          path: client/build/compose/binaries/main-release/app/ChatApp
          if-no-files-found: error
      - name: Build server with Gradle
        run: "./gradlew server:shadowJar"
      - name: Upload a server Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Server JAR
          path: server/build/libs/*.jar
          if-no-files-found: error